# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RuIjIfKA8zgAh5YlzMhHjp2ACA-Dajrh
"""









# Manipulation de données
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Modèles de Machine Learning
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# Deep Learning (optionnel si tu veux utiliser Keras/TensorFlow)


# Prétraitement et pipeline
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, cross_validate
from sklearn.preprocessing import MinMaxScaler
from imblearn.combine import SMOTEENN
from imblearn.pipeline import Pipeline as ImbPipeline

# Évaluation et métriques
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, mean_absolute_error, mean_squared_error,
    classification_report, confusion_matrix, roc_curve,
    precision_recall_curve, ConfusionMatrixDisplay, make_scorer
)

# Optimisation
import optuna
from optuna.samplers import TPESampler, CmaEsSampler, QMCSampler

# Sauvegarde / chargement
import joblib

import pandas as pd

# ID de ton fichier Google Drive (depuis le lien que tu as donné)
file_id = "1QYe6dmwvmz73PaYVZ9VV1TnBDtl7C9i1"

# URL de téléchargement direct
url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Charger le CSV depuis Google Drive
df = pd.read_csv("telco_churn_preprocessed.csv")
# Vérifier
print("Shape du dataset :", df.shape)
print(df.head())

# =======================================================
# 1. Préparation des données
# =======================================================
print("🚀 Préparation des données...")
try:
    df = pd.read_csv("telco_churn_preprocessed.csv")
except FileNotFoundError:
    print("Erreur: Le fichier 'telco_churn_preprocessed.csv' n'a pas été trouvé.")
    exit()

X = df.drop("Churn", axis=1)
y = df["Churn"]

# Normalisation des features
scaler = MinMaxScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

# Séparation des ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Rééquilibrage des données d'entraînement avec SMOTEENN
smoten = SMOTEENN(random_state=42)
X_train_res, y_train_res = smoten.fit_resample(X_train, y_train)

print("✅ Données prêtes.")

# =======================================================
# 2. Entraînement du modèle CatBoost avec les meilleurs paramètres
# =======================================================
print("\n🧠 Entraînement du modèle CatBoost...")

# Les meilleurs paramètres que vous avez déjà fournis
best_catboost_params = {
    'iterations': 422,
    'depth': 12,
    'learning_rate': 0.04940621051278419,
    'l2_leaf_reg': 0.05491553217081499,
    'random_strength': 4.636852689665369,
    'grow_policy': 'SymmetricTree'
}

catboost_model = CatBoostClassifier(
    **best_catboost_params,
    logging_level="Silent",
    random_seed=42
)

catboost_model.fit(X_train_res, y_train_res)
print("✅ Modèle entraîné.")

# =======================================================
# 3. Optimisation du seuil et évaluation
# =======================================================
print("\n📊 Évaluation des performances avec optimisation du seuil...")
y_prob = catboost_model.predict_proba(X_test)[:, 1]

# Optimisation du seuil pour maximiser le F1-score de la classe minoritaire
best_threshold = 0.5
best_f1_minority = 0
for threshold in np.arange(0.1, 0.9, 0.01):
    y_pred_temp = (y_prob >= threshold).astype(int)
    f1_minority = f1_score(y_test, y_pred_temp)
    if f1_minority > best_f1_minority:
        best_f1_minority = f1_minority
        best_threshold = threshold

y_pred_final = (y_prob >= best_threshold).astype(int)

# Affichage des métriques complètes
print(f"Meilleur seuil de classification trouvé: {best_threshold:.2f}")
print("\n--- Rapport de Classification ---")
print(classification_report(y_test, y_pred_final, zero_division=0))

print("\n--- Métriques d'erreur et de précision ---")
mae = mean_absolute_error(y_test, y_pred_final)
mse = mean_squared_error(y_test, y_pred_final)
roc_auc = roc_auc_score(y_test, y_prob)

print(f"MAE : {mae:.4f}")
print(f"MSE : {mse:.4f}")
print(f"ROC AUC : {roc_auc:.4f}")

# Normalisation des features
scaler = MinMaxScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
print("✅ Données prêtes.")

# =======================================================
# 2. Définition du pipeline et de la validation croisée
# =======================================================
print("\n🧠 Définition du pipeline et de la stratégie de validation...")
best_catboost_params = {
    'iterations': 422,
    'depth': 12,
    'learning_rate': 0.04940621051278419,
    'l2_leaf_reg': 0.05491553217081499,
    'random_strength': 4.636852689665369,
    'grow_policy': 'SymmetricTree'
}

pipeline = ImbPipeline([
    ('smoteenn', SMOTEENN(random_state=42)),
    ('catboost', CatBoostClassifier(**best_catboost_params, logging_level="Silent", random_seed=42))
])

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
print("✅ Pipeline et stratégie définis.")

# =======================================================
# 3. Évaluation par validation croisée (10 plis)
# =======================================================
print("\n📊 Évaluation par validation croisée stratifiée (10 plis)...")
# Note : Pour les graphiques, on va ré-entraîner sur tout l'ensemble de données.
print("✅ Évaluation terminée.")

# Re-entraînement du modèle sur tout l'ensemble de données pour la prédiction finale
pipeline.fit(X, y)

# =======================================================
# 4. Prédiction et rapport final
# =======================================================
print("\n🎯 Rapport final du modèle entraîné sur toutes les données...")
y_prob_final = pipeline.predict_proba(X)[:, 1]

# Optimisation du seuil pour le meilleur F1-score macro
thresholds = np.arange(0.1, 0.9, 0.01)
best_threshold = 0.5
best_f1_macro = 0
for threshold in thresholds:
    y_pred_temp = (y_prob_final >= threshold).astype(int)
    f1_macro_temp = f1_score(y, y_pred_temp, average='macro', zero_division=0)
    if f1_macro_temp > best_f1_macro:
        best_f1_macro = f1_macro_temp
        best_threshold = threshold

y_pred_final = (y_prob_final >= best_threshold).astype(int)

# =======================================================
# 4. Prédiction et rapport final (ajout visualisations)
# =======================================================
print("\n🎯 Rapport final du modèle entraîné sur toutes les données...")

# Probabilités
y_prob_final = pipeline.predict_proba(X)[:, 1]

# Optimisation du seuil
thresholds = np.arange(0.1, 0.9, 0.01)
best_threshold = 0.5
best_f1_macro = 0
for threshold in thresholds:
    y_pred_temp = (y_prob_final >= threshold).astype(int)
    f1_macro_temp = f1_score(y, y_pred_temp, average='macro', zero_division=0)
    if f1_macro_temp > best_f1_macro:
        best_f1_macro = f1_macro_temp
        best_threshold = threshold

y_pred_final = (y_prob_final >= best_threshold).astype(int)

# Affichage des métriques
print(f"\nMeilleur seuil de classification trouvé: {best_threshold:.2f}")
print("\n--- Rapport de Classification ---")
print(classification_report(y, y_pred_final, zero_division=0))

print("\n--- Métriques d'erreur et de précision ---")
mae = mean_absolute_error(y, y_pred_final)
mse = mean_squared_error(y, y_pred_final)
roc_auc = roc_auc_score(y, y_prob_final)

print(f"MAE : {mae:.4f}")
print(f"MSE : {mse:.4f}")
print(f"ROC AUC : {roc_auc:.4f}")

# =======================================================
# 🔍 Visualisations
# =======================================================

# 1. Matrice de confusion
cm = confusion_matrix(y, y_pred_final)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False,
            xticklabels=["Classe 0", "Classe 1"],
            yticklabels=["Classe 0", "Classe 1"])
plt.title("Matrice de confusion")
plt.xlabel("Prédictions")
plt.ylabel("Réel")
plt.show()

# =======================================================
# Matrice de confusion sur le jeu de test
# =======================================================
print("\n📌 Matrice de confusion sur le jeu de test :")

# Prédictions sur le test
y_prob_test = pipeline.predict_proba(X_test)[:, 1]
y_pred_test = (y_prob_test >= best_threshold).astype(int)

# Matrice de confusion brute
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)

# Heatmap avec Seaborn
plt.figure(figsize=(6,5))
sns.heatmap(cm_test, annot=True, fmt="d", cmap="Blues", cbar=False,
            xticklabels=["Classe 0 (prédit)", "Classe 1 (prédit)"],
            yticklabels=["Classe 0 (réel)", "Classe 1 (réel)"])
plt.title("🧩 Matrice de confusion (jeu de test)")
plt.xlabel("Prédictions")
plt.ylabel("Vérités terrain")
plt.show()

# Alternative officielle scikit-learn
disp = ConfusionMatrixDisplay(confusion_matrix=cm_test,
                              display_labels=["Classe 0", "Classe 1"])
disp.plot(cmap="Blues", values_format="d")
plt.title("🧩 Matrice de confusion (jeu de test)")
plt.show()

# 2. Courbe ROC
fpr, tpr, _ = roc_curve(y, y_prob_final)
plt.figure(figsize=(7,6))
plt.plot(fpr, tpr, label=f"ROC AUC = {roc_auc:.3f}")
plt.plot([0,1], [0,1], linestyle="--", color="gray")
plt.xlabel("Taux de faux positifs (FPR)")
plt.ylabel("Taux de vrais positifs (TPR)")
plt.title("Courbe ROC")
plt.legend()
plt.show()

# 3. Courbe Precision-Recall
prec, rec, _ = precision_recall_curve(y, y_prob_final)
plt.figure(figsize=(7,6))
plt.plot(rec, prec, label="Courbe Precision-Recall")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Courbe Precision-Recall")
plt.legend()
plt.show()

# 4. Histogramme des probabilités prédites
plt.figure(figsize=(7,5))
sns.histplot(y_prob_final[y==0], color="red", label="Classe 0", kde=True, bins=30)
sns.histplot(y_prob_final[y==1], color="blue", label="Classe 1", kde=True, bins=30)
plt.axvline(x=best_threshold, color="black", linestyle="--", label=f"Seuil {best_threshold:.2f}")
plt.xlabel("Probabilités prédites")
plt.ylabel("Fréquence")
plt.title("Distribution des probabilités par classe")
plt.legend()
plt.show()

# 5. Barres comparatives des métriques
metrics = {
    "Accuracy": accuracy_score(y, y_pred_final),
    "Precision": precision_score(y, y_pred_final),
    "Recall": recall_score(y, y_pred_final),
    "F1 Macro": f1_score(y, y_pred_final, average="macro"),
    "ROC AUC": roc_auc
}

plt.figure(figsize=(8,5))
sns.barplot(x=list(metrics.keys()), y=list(metrics.values()), palette="viridis")
plt.ylim(0,1)
plt.ylabel("Score")
plt.title("Comparaison des métriques")
for i, val in enumerate(metrics.values()):
    plt.text(i, val+0.02, f"{val:.3f}", ha="center")
plt.show()
joblib.dump((pipeline, X.columns.tolist()), "catboost_churn.pkl")
print("✅ Modèle et colonnes sauvegardés : catboost_churn.pkl")